/*
* Generated file
*
* Generated from: yang module name: odl-netconfig-client-cfg yang module local name: netconf-client-dispatcher
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Oct 06 17:55:37 EDT 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.netconf.client.dispatcher;
public class NetconfClientDispatcherModuleFactory extends org.opendaylight.controller.config.yang.config.netconf.client.dispatcher.AbstractNetconfClientDispatcherModuleFactory {

}
