<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="23">
<data>
<network-topology xmlns="urn:TBD:params:xml:ns:yang:network-topology">
<topology>
<topology-id>topology-netconf</topology-id>
<node>
<node-id>controller-config</node-id>
</node>
</topology>
</network-topology>
<nodes xmlns="urn:opendaylight:inventory">
<node>
<id>controller-config</id>
</node>
</nodes>
</data>
</rpc-reply>
