/*
 * Copyright (c) 2017 Inocybe Technologies and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/**
 * This package contains the statistical JMX classes for the Draft02 restconf implementation. Originally these classes
 * were generated by the CSS code generator and were moved to this package on conversion to blueprint.
 */
package org.opendaylight.netconf.sal.restconf.impl.jmx;
