/*
 * Copyright (c) 2015 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: netconf-northbound-impl yang module local name: netconf-server-monitoring-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Feb 17 17:24:19 CET 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.netconf.northbound.impl;

import org.opendaylight.controller.config.api.DependencyResolver;
import org.osgi.framework.BundleContext;

/**
 * @deprecated Replaced by blueprint wiring
 */
@Deprecated
public class NetconfServerMonitoringModuleFactory extends AbstractNetconfServerMonitoringModuleFactory {

    @Override
    public NetconfServerMonitoringModule instantiateModule(String instanceName, DependencyResolver dependencyResolver,
                                                           NetconfServerMonitoringModule oldModule, AutoCloseable oldInstance, BundleContext bundleContext) {
        NetconfServerMonitoringModule module = super.instantiateModule(instanceName, dependencyResolver, oldModule,
                oldInstance, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }

    @Override
    public NetconfServerMonitoringModule instantiateModule(String instanceName, DependencyResolver dependencyResolver,
                                                           BundleContext bundleContext) {
        NetconfServerMonitoringModule module = super.instantiateModule(instanceName, dependencyResolver, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }
}
