odl:
  netconf:
    prototype:
      in-memory-datastore:
        operational:
          max-data-change-executor-queue-size: 1000
          max-data-change-executor-pool-size: 20
          max-data-change-listener-queue-size: 1000
          max-data-store-executor-queue-size: 5000
          debug-transaction: false

        configuration:
          max-data-change-executor-queue-size: 1000
          max-data-change-executor-pool-size: 20
          max-data-change-listener-queue-size: 1000
          max-data-store-executor-queue-size: 5000
          debug-transaction: false

      cluster-datastore-broker:
        max-data-broker-future-callback-queue-size: 1000
        max-data-broker-future-callback-pool-size: 20
