inmemory-datastore:
  operational:
    max-data-change-executor-queue-size: 1000
    max-data-change-executor-pool-size: 20
    max-data-change-listener-queue-size: 1000
    max-data-store-executor-queue-size: 5000
    debug-transaction: false

  configuration:
    max-data-change-executor-queue-size: 1000
    max-data-change-executor-pool-size: 20
    max-data-change-listener-queue-size: 1000
    max-data-store-executor-queue-size: 5000
    debug-transaction: false

cluster-datastore-broker:
  max-data-broker-future-callback-queue-size: 1000
  max-data-broker-future-callback-pool-size: 20

shiro-configuration:
  main:
    # Hardcode 'admin:admin' credentials directly into Shiro for testing, avoiding the need for an underlying
    # AAA database.
    "textRealm": org.apache.shiro.realm.text.TextConfigurationRealm
    "textRealm.userDefinitions": "admin=admin,admin"
    "securityManager.realms": $textRealm

    "accountingListener": org.opendaylight.aaa.shiro.filters.AuthenticationListener
    "securityManager.authenticator.authenticationListeners": $accountingListener
    "dynamicAuthorization": org.opendaylight.aaa.shiro.realm.MDSALDynamicAuthorizationFilter
    "invalidRequest.blockSemicolon": "false"
    "invalidRequest.blockEncodedForwardSlash": "false"
    "invalidRequest.blockEncodedPeriod": "false"
  urls:
    "/**/operations/cluster-admin**": "authcBasic, roles[admin]"
    "/**/v1/**": "authcBasic, roles[admin]"
    "/**/data/aaa*/**": "authcBasic, roles[admin]"
    "/**": "authcBasic"

aaa-cert-service-config:
  use-config: true
  use-mdsal: true
  bundle-name: opendaylight
  ctl-keystore:
    name: ctl.jks
    alias: controller
    store-password: ""
    dname: "CN=ODL, OU=Dev, O=LinuxFoundation, L=QC Montreal, C=CA"
    validity: 365
    key-alg: RSA
    sign-alg: SHA1WithRSAEncryption
    keysize: 1024
    tls-protocols: []
    cipher-suites:
      - ""
  trust-keystore:
    name: truststore.jks
    store-password: ""

rfc8040-configuration:
  # pretty-print: false
  # data-missing-is-404: false
  # maximum-fragment-length: 0
  # heartbeat-interval: 10000
  # restconf: rests
  # ping-executor-name-prefix: ping-executor
  # max-thread-count: 1

  # Netty endpoint related settings
  # bind-address: "0.0.0.0"
  # bind-port: 8182
  # api-root-path: restconf
  # boss-threads: 0
  # worker-threads: 0
  # http-chunk-size: 262144
  # default-encoding: json
  # http2-max-frame-size: 16384
  # http3-alt-svc-max-age: 0
  # http3-initial-max-data: 4194304
  # http3-initial-max-stream-data-bidirectional-remote: 262144
  # http3-initial-max-streams-bidirectional: 100

  # Netty Tls transport configuration.
  tls-certificate: etc/tls/cert.pem
  # Private key file in PEM format
  tls-private-key: etc/tls/key.pem
