/*
 * Copyright (c) 2016 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */
/*
* Generated file
*
* Generated from: yang module name: odl-restconf-sb-connector yang module local name: restconf-sb-connector
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri May 06 12:38:37 CEST 2016
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.md.sal.connector.restconf.sb;
public class RestconfSbConnectorModuleFactory extends org.opendaylight.controller.config.yang.md.sal.connector.restconf.sb.AbstractRestconfSbConnectorModuleFactory {

}
