/*
 * Copyright (c) 2015 Cisco Systems, Inc. and others.  All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: netconf-mdsal-mapper yang module local name: netconf-mdsal-mapper
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Jan 14 14:58:42 CET 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.netconf.mdsal.mapper;

import org.opendaylight.controller.config.api.DependencyResolver;
import org.osgi.framework.BundleContext;

/**
 * @deprecated Replaced by blueprint wiring
 */
@Deprecated
public class NetconfMdsalMapperModuleFactory extends AbstractNetconfMdsalMapperModuleFactory {
    @Override
    public NetconfMdsalMapperModule instantiateModule(String instanceName, DependencyResolver dependencyResolver,
                                                      NetconfMdsalMapperModule oldModule, AutoCloseable oldInstance, BundleContext bundleContext) {
        NetconfMdsalMapperModule module = super.instantiateModule(instanceName, dependencyResolver, oldModule,
                oldInstance, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }

    @Override
    public NetconfMdsalMapperModule instantiateModule(String instanceName, DependencyResolver dependencyResolver,
                                                           BundleContext bundleContext) {
        NetconfMdsalMapperModule module = super.instantiateModule(instanceName, dependencyResolver, bundleContext);
        module.setBundleContext(bundleContext);
        return module;
    }
}
